name: simplesvr
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Tanger John <email@example.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2

#dev_dependencies:
#  test: ^0.12.30
