name: websvr30
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  aqueduct: ^3.0.0-alpha.1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  aqueduct_test: ^1.0.0-alpha.1

dependency_overrides:
  aqueduct:
    path:  /home/tanger/devprojects/aqueduct/aqueduct/
  aqueduct_test:
    path:  /home/tanger/devprojects/aqueduct/aqueduct_test/
